docs/about.md, docs/index.md, mkdocs.yml
This PR creates a document stub using mkdocs: https://www.mkdocs.org/getting-started/
This documentation can easily be imported into readthedocs.
=> added mkdocs stub

tests/test_terra_model.py
This PR adds the first unit test to TerraTools.
=> added first test

.github/workflows/main.yml, test.sh
This PR sets up a GitHub workflow to check the installation of the module, the indentation and the test suite.
=> added test workflow

pyproject.toml
Move the build system to Poetry since this seems easier for
Andy to understand and get working quickly.
=> Change build system to Poetry

.gitignore, examples/example_attenuation.py, examples/example_perplex.py, terratools/properties/__init__.py, terratools/properties/attenuation.py, terratools/properties/data/perplex_build_template.txt, terratools/properties/data/perplex_option.dat, terratools/properties/perplex.py, tests/test_attenuation.py
This PR adds the tools required to make a terra-readable properties table using PerpleX.
PerpleX is not bundled with TerraTools, so the example is only partially run. The full script has been tested locally.
=> added terra property grid creator

examples/example_attenuation.py, examples/example_perplex.py, terratools/properties/attenuation.py, terratools/properties/perplex.py
This PR adds code documentation for the functions in the properties submodule (attenuation.py and perplex.py).
=> added code documentation for properties submodule

.github/workflows/draft-pdf.yml, paper/paper.bib, paper/paper.md
Added a skeletal JOSS paper with associated bib file (in paper/). Added an action to compile the PDF on push. 
* [-] I have run the [`contrib/utilities/indent`](../blob/main/contrib/utilities/indent) script from the main directory to indent my code.
(N/A for files added).
=> Joss paper

paper/paper.md
This PR adds the ORCID for Bob. Also corrects a couple of typos.
=> JOSS paper: add orcid

.github/workflows/main.yml
This PR adds installation of libgeos-dev to the GitHub workflow yml file.
=> added libgeos-dev to GitHub actions

docs/api/terra_model.md, docs/requirements.txt, mkdocs.yml
This PR adds TerraModel autogenerated documentation
=> started API docs

readthedocs.yaml
Adds a yaml file for readthedocs.
=> add readthedocs yaml

docs/requirements.txt
Added mkdocstrings=0.19.0 and mkdocs-material=8.5.6
=> added new requirements for docs

docs/api/properties/perplex.md, docs/api/properties/profiles.md, docs/api/properties/utilities.md, docs/index.md, docs/references.bib, docs/requirements.txt, docs/zz_bibliography.md, mkdocs.yml, terratools/properties/attenuation.py, terratools/properties/perplex.py, terratools/properties/profiles.py, terratools/properties/utilities.py
This PR updates the docstrings for the properties submodule.
=> updated docstrings for properties submodule

docs/api/properties/attenuation.md, docs/api/properties/perplex.md, docs/api/properties/profiles.md, docs/api/properties/utilities.md, docs/api/terra_model.md, docs/gen_ref_pages.py, docs/index.md, docs/requirements.txt, mkdocs.yml
This PR creates fully automated code documentation, addressing Issue #54.
=> created synched autodocumentation

docs/references.bib, docs/zz_bibliography.md, terratools/properties/attenuation.py, terratools/properties/perplex.py, terratools/properties/profiles.py, terratools/properties/utilities.py
This PR adds literature references to the documentation for the properties submodule.
Can be tweaked if there is a fix for Issue #53, but this looks ok.
=> added references for properties submodule

docs/zz_bibliography.md
This PR removes the subscripted letters from the rendered bibliography.
=> cleaned bibliography

terratools/__init__.py, terratools/geographic.py, terratools/lookup_tables.py, terratools/plot.py, terratools/terra_model.py
This PR tidies up some of the docstrings in the project.
=> some doc tidying

docs/javascript/mathjax.js, docs/properties.md, mkdocs.yml, terratools/properties/attenuation.py
This PR extends the documentation for the properties submodule.
=> added documentation for properties submodules

docs/copy_ref_examples.py, docs/gen_ref_pages.py, mkdocs.yml, readthedocs.yaml
Prebuild examples for readthedocs
=> prebuild examples for RTD

docs/requirements.txt, docs/zz_bibliography.md, mkdocs.yml, terratools/properties/attenuation.py, terratools/properties/perplex.py, terratools/properties/profiles.py, terratools/properties/utilities.py
This PR improves the bibtex referencing method.
=> change referencing method

terratools/lookup_tables.py, tests/test_lookup_table.py
Add several arguments to the `SeismicLookupTable` constructor, one for
each property read from a table, allowing one to create an instance
without having to read files from disk.  Passing a single argument
still reads a file from disk, however, meaning this change is
backwards-compatible.
Along the way, tidy up the internal state held by `SeismicLookupTable`:
- Remove `.P` and `.T`.  This requires changes in:
- `plot_table` and
- `plot_table_contour`.
- Remove `.table` as once we have used this when reading a file we no
longer need to retain it in memory.
- Remove `.n_uniq_p` and `.n_uniq_t` as these were unused.
- Remove `.pstep` as this was only used for converting the data read
from a file
- Rename things to be all lowercase.
Pull Request Checklist. Please read and check each box with …
=> SeismicLookupTable: Enable construction from data

examples/example_convert.py, misc/ref/example_convert.py.out, terratools/convert_files.py
Added a short example of how to convert files. 
This is pretty much the same as the test for covert_files but I felt that having something in the examples directory makes it more visible to users. 
* [ X] I have run the [`contrib/utilities/indent`](../blob/main/contrib/utilities/indent) script from the main directory to indent my code.
* [ X] I have tested my new feature locally to ensure it is correct.
=> Add example for convert_files

terratools/terra_model.py, tests/test_adiabat.py
*Describe what you did in this PR and why you did it.*
=> Add adiabat

terratools/geographic.py, terratools/terra_model.py, tests/test_geographic.py, tests/test_terra_model.py
This PR vectorises the `spherical_triangle_area` function in `geographic.py` and `TerraModel.evaluate` in `terra_model.py`.
Test cases are also added.
=> vectorised spherical triangle area

examples/example_healpy.py, terratools/terra_model.py, tests/test_terra_model.py
Changes the name of function `get_bulk_composition` to `calc_bulk_composition` - #96
=> change `get_bulk_composition` to `calc_bulk_composition`

paper/paper.bib, paper/paper.md
*Describe what you did in this PR and why you did it.*
I have added references for the paper related to other codes, and added the references in the .bib file. 
* [ x] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.
=> Added some references to paper.md and paper.bib

terratools/terra_model.py
Fix to the plot_hp_map function which would throw an error when passing in a radius (#109 )
=> Fix to plot_hp_map when passing in a radius

docs/file_formats.md
Fixing syntax problems in `docs/file_formats.md`
=> Fix syntax in file_formats.md

terratools/plume_detection.py
Update to calculate the centroid of each layer of a plume, rather than the centroid of the plume as a whole.
=> Correction to the centroid calculation

terratools/terra_model.py
Adding isotopes that are tracked in Terra to dictionaries of fields which are allowed to be present in a TerraModel.
=> Accept geochemical fields

terratools/terra_model.py
Allowing ppv to be added as a scalar field to map ppv abundance in model.
=> Allow ppv as a scalar field 

README.md, changelog.txt, pyproject.toml, terratools/__init__.py
Merge `terratools-1.0` into `main`
=> Terratools 1.0

changelog.txt, pyproject.toml, terratools/terra_model.py
This PR addresses #146 to allow users to add a new field to the TerraModel with an arbitrary name.
=> Add arbitrary fields

changelog.txt, examples/example_plume_detect.py, terratools/plot.py, terratools/terra_model.py
In this PR, functions have been updates to allow plotting / calculation of spherical harmonics of individual components of vector fields. In particular the functions:
* `plot_section`
* `plot_layer`
* `plot_spectral_heterogeneity`
*  `plot_hp_map`
*  `calc_spectral_heterogeneity`
=> Plot individual components of vector fields

README.md, terratools/__init__.py
Add updated DOIs to main branch
=> terratools v1.1.0 updated DOIs

changelog.txt
Add mention of the bugfix to the changelog, as should have
been done in the original PR (#165).
=> Update changelog for file reading bugfix

CONTRIBUTING.md
Since running the tests requires the developer dependencies,
add this to the `CONTRIBUTING.md` file rather than the
README.
=> Explain how to run tests

.github/workflows/main.yml
Check Python versions up to v3.12.
=> CI: Check newer Python versions and output package versions
