CONTRIBUTING.md, README.md, docs/index.md, pyproject.toml
The module name `terra_tools` would be transformed to `terra-tools`
by PyPI, so mush the words together and call it `terratools`.
This commit changes all the names but does not change any website
addresses externally.
*Describe what you did in this PR and why you did it.*
=> Rename project to terratools

pyproject.toml, terratools/terra_model.py, tests/test_terra_model.py
Add three new methods for `TerraModel`s:
- `nearest_neighbors` for `n` nearest neighbours, giving both the point index and distance;
- `nearest_indices`, giving just the `n` nearest point indices; and
- `nearest_index`, giving just the index of the nearest lateral point.
These will be useful for interpolation routine, to come.
=> Add nearest-neighbour lookup for `TerraModel`s

terratools/terra_model.py, tests/test_terra_model_read_netcdf.py
As well as NetCDF files containing just the flow field and
composition histograms, TERRA will also output files containing
seismic velocities and density.  Add support for reading these.
~Marked as 'WIP' because there are still no tests for reading
such NetCDF files!~  There is now a test.
=> Add reading for 'seismic' NetCDF files

pyproject.toml, terratools/plot.py, terratools/terra_model.py, tests/test_plot.py, tests/test_terra_model.py
Add `TerraModel.plot_layer` function to plot a single layer of a field
within a `TerraModel`.  This is currently limited to the nearest layer,
but in future should allow for arbitrary radii to be specified.
=> Add method to plot a layer

terratools/geographic.py
No mention was made of the `val1`, `val2` or `val3`
parameters.
=> geographic: Fix missing parameters in docstring

.gitignore, docs/copy_ref_examples.py, docs/requirements.txt, examples/example_attenuation.py, mkdocs.yml
This PR adds an example script to the documentation. The new required module `mkdocs-jupyter` can be used with either py or ipynb files.
=> add example to docs

terratools/terra_model.py, tests/test_terra_model.py
NetCDF files which contain any variables which have unexpected
names previously meant that `terra_model._field_name_from_variable`
raised a `KeyError`.  Update the function to return `None` instead
when given a NetCDF variable name which we are not expecting to
read.
This was encountered when using `convert_files.convert` to update
old-format NetCDF files without the `ncks` program, which left
old variables in files which are now unexpected.
Although one could argue that requiring files do not have extra,
unexpected variables is a good feature of the reader, implementing
the behaviour introduced by this commit does mean that old code
should be able to continue to read newer file versions which only
add new variables.
=> Fix reading of NetCDF files with extra variables

.github/workflows/main.yml, contrib/utilities/indent
This PR forces github actions to use black 22.12 and makes the indent script use version 22.x.
=> Black version

.github/workflows/main.yml, README.md, pyproject.toml, terratools/plot.py, test.sh, tests/test_plot.py, tests/test_terra_model.py
This means that users must install cartopy separately if they want to
make maps which use cartopy, via `pip` or otherwise.
Update the test script to install cartopy unconditionally.  A future
commit will add a test for the correct behaviour (an `ImportError`)
when trying to call a function which relies on cartopy.
*Describe what you did in this PR and why you did it.*
[`contrib/utilities/indent`](../blob/main/contrib/utilities/indent) script from the main directory to indent my code.
[tests/](../blob/main/tests/) directory.
=> Make cartopy an optional dependency

terratools/terra_model.py
Added capability to read a single netcdf file that is a concatenation of netcdf files of a single time step dump. Such files are create using `ncecat` which is available though netCDF Operators (NCO). This is useful for users who locally store lots of model output, where having a single concatenated netCDF file for each dump is more manageable than having a file for each process for each dump.
=> Read concatenated files

terratools/terra_model.py, tests/test_1d_profile.py
Rename a function to conform to the convention for methods of `TerraModel` and ensure that the argument order for longitude and latitude is the same everywhere.
- terra_model: Rename `get_1d_mean` to `mean_1d_profile`
- terra_moel: Update coordinate order of `get_1d_profile`
=> Fix naming and calling conventions for profiles

terratools/terra_model.py, tests/test_terra_model.py
Sometimes `test_plot_section` errors because too few points are
calculated with the default radial spacing.  ~Try to fix this by
increasing the number of layers in the random model created.~ Fix this within `TerraModel.plot_section` by accounting for this possibiliy, and test the fix works.
=> TerraModel.plot_section: Try to fix intermittent random test failures

mkdocs.yml
Fixes readthedocs build failing as a result of mkdocstrings breaking changes:
`https://github.com/mkdocstrings/mkdocstrings/releases/tag/0.23.0`
=> removed deprecated watch feature from mkdocs

examples/example_cross_section.py, examples/example_plot_flowfield.py, examples/example_plot_map.py, examples/example_plume_detect.py, examples/example_spherical_harmonics.py, terratools/plot.py, terratools/terra_model.py, tests/test_plot.py, tests/test_terra_model.py
In this PR, which relates to #115 , I have added the ability to pass in figure and axis handles into some of the plotting routines, namely `plot_layer`, `plot_section`, `plot_spectral_heterogeneity` and `plot_hp_map`. 
I have also made these functions return the handle to the colorbar to allow greater flexibility to users when producing figures. As such calls to these plotting functions in tests and examples have been updated in this PR.
=> Allowing plotting to existing axes

changelog.txt, examples/example_cross_section.py, examples/example_plot_map.py, examples/example_spherical_harmonics.py, terratools/plot.py, terratools/terra_model.py, tests/test_plot.py, tests/test_terra_model.py
Addressing comment on #152 to only return `cbar` from plotting functions if requested by passing `return_cbar=True`.
This will prevent the breaking change to allow backwards compatibility.
=> return cbar from plotting functions only if passed `return_cbar=True`

terratools/terra_model.py
Changed lambda function definition for PREM pressure to a named function definition so model pickling works. Fixes issue #158.
=> Fixed definition of PREM pressure function to allow model pickling to work

terratools/properties/profiles.py
Fix the docstrings of
`properties.profiles.Simon_Glatzel_lower_mantle_Fiquet`
and `properties.profiles.peridotite_solidus` to correctly describe
the units of pressure as Pa, not GPa as previously and incorrectly
given.
[`contrib/utilities/indent`](../blob/main/contrib/utilities/indent) script from the main directory to indent my code.
=> Fix incorrect docstring for solidus pressure units

.github/workflows/draft-pdf.yml, .github/workflows/main.yml
Some CI runs are currently failing because we use a version of
`actions/upload-artifact` which is too old
(https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/).
Replace these uses with the latest version to fix the CI runs.
Longer term, updating them automatically may be prudent
(https://github.com/mantle-convection-constrained/terratools/issues/172).
=> CI: Update the upload-artifact GitHub action version

terratools/convert_files.py
Python 3.13 moves distutils into setuptools, so replace the
use of `distutils.span.find_executable` with `shutil.which`
in the example script which uses it.
[`contrib/utilities/indent`](../blob/main/contrib/utilities/indent) script from the main directory to indent my code.
=> Replace the use of distutils with shutil

.github/dependabot.yml
Use Dependabot to open PRs to update out CI workflow when the GitHub Actions we use are updated.
=> Add Dependabot to update GitHub actions
